from __future__ import annotations
from typing import Literal, Optional, List
from pydantic import BaseModel, Field, model_validator


class TimeRange(BaseModel):
    start: float = Field(description="Start time in seconds, 0.1s precision")
    end: float = Field(description="End time in seconds, 0.1s precision")


class EventTimestamp(BaseModel):
    time: float = Field(description="Event occurrence time in seconds, 0.1s precision")
    type: Literal["onset", "accent", "continuous_start"]
    intensity: Optional[Literal["soft", "medium", "loud"]] = None


class AudioEvent(BaseModel):
    description: str = Field(
        description="Detailed sound description: material, action, intensity, texture, rhythm"
    )
    source_visible: bool = Field(
        description="True if sound source is clearly visible on screen; False if off-screen or ambiguous"
    )
    time_range: TimeRange = Field(description="Overall time range of this sound event")
    event_timestamps: List[EventTimestamp] = Field(
        default_factory=list,
        description="Individual onset/impact moments. Empty list for continuous sounds with no discrete events.",
    )
    # post-analysis fields (NOT generated by LLM; assigned by assemble.py)
    group_id: Optional[str] = Field(default=None)
    canonical_description: Optional[str] = Field(default=None)

    @model_validator(mode="after")
    def validate_timestamps_in_range(self) -> "AudioEvent":
        for ts in self.event_timestamps:
            if not (
                self.time_range.start - 0.1 <= ts.time <= self.time_range.end + 0.1
            ):
                raise ValueError(
                    f"event_timestamp {ts.time}s is outside "
                    f"time_range [{self.time_range.start}, {self.time_range.end}]"
                )
        return self


class Scene(BaseModel):
    scene_index: int = Field(description="0-based scene index")
    time_range: TimeRange = Field(description="Time range of this scene")
    background_ambience: str = Field(
        description="Continuous environmental/atmospheric background sound only. Must NOT include sounds described in audio_events."
    )
    audio_events: List[AudioEvent] = Field(
        description="All distinct sound-producing events in this scene. No count limit.",
        default_factory=list,
    )
    # post-analysis fields
    background_group_id: Optional[str] = Field(default=None)
    background_canonical: Optional[str] = Field(default=None)


class VideoSceneAnalysis(BaseModel):
    total_duration: float = Field(description="Total video duration in seconds")
    scenes: List[Scene] = Field(description="List of scenes detected in the video")
